version: "3.8"

services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes: #volumes might not work on windows
      - ./frontend:/app/frontend
      - ./app/frontend/node_modules
